---
## Playbook to deploy a Dockerized ELK stack

- name: Deploy ec2 instance
  gather_facts: false
  hosts: localhost
  roles:
    - aws
  tags:
    - deploy

- name: Deploy Elk Server
  hosts: elk-server
  become: yes
  roles:
    - docker
    - elk-docker
  tags: 
    - elk

- name: Deploy Filebeat
  hosts: filebeat
  become: yes
  roles:
    - filebeat
  tags:
    - filebeat
