---

# Playbook to deploy a Dockerized ELK stack

- name: Deploy ec2 instance
  gather_facts: false
  hosts: localhost
  roles:
    - aws
  tags:
    - deploy

- name: Deploy Elk Server
  hosts: elk-server
  become: yes
  become_user: root
  remote_user: ec2-user
  roles:
    - users
    - docker
    - elk-docker
  tags: 
    - elk

- name: Deploy Filebeat
  hosts: elk-server
  become: yes
  become_user: root
  remote_user: ec2-user
  roles:
    - filebeat
  tags:
    - filebeat
