---

- name: Deploy ec2 instance
  ec2:
    region: "{{ ec2_region }}"
    key_name: elk
    group: elk_sg
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: true
    exact_count: "{{ ec2_count }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: true
    instance_tags:
      Name: elk-server
      Role: Dockerized-Elk
      Creator: Carlos Francia
      Tool: Ansible
    count_tag:
      Name: elk-server
  register: ec2

# - name: debug Hostvars
#  debug:
#    var: hostvars

# - name: debug ec2
#  debug:
#    var: ec2.tagged_instances

- name: Add instances to elk server group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: elk-server
  with_items: "{{ ec2.tagged_instances }}"

# - name: debug Hostvars2
#  debug:
#    var: hostvars

- name: Wait dor ec2 instance to come online
  wait_for:
    port: 22
    host: "{{ item.public_dns_name }}"
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.tagged_instances }}"

