---

- name: Create ec2 Security Group
  ec2_group:
    name: elk_sg
    description: ELK Security group
    vpc_id: "{{ vpc_id }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5601
        to_port: 5601
        cidr_ip: 0.0.0.0/0

